add python support for oms_exportSSVTemplate
OpenModelica/OMSimulator pull request #864
Opened 2020-11-10 14:16 UTC by arun3688

### Related Issues

https://github.com/OpenModelica/OMSimulator/issues/824

### Purpose

This PR implements python support to  `oms_exportSSVTemplate`  API

2020-11-10 15:14 UTC, lochel requested changes

2020-11-10 15:14 UTC, lochel commented on doc/UsersGuide/source/api/exportSSVTemplate.rst
> +--------------
`---`

2020-11-10 15:19 UTC, arun3688 commented on doc/UsersGuide/source/api/exportSSVTemplate.rst
> +--------------
fixed with https://github.com/OpenModelica/OMSimulator/pull/864/commits/08d59dce891dbd9bb98a4905c6f7c402aac5ddb0

2020-11-11 17:41 UTC, merged

2020-11-19 13:35 UTC, robha67 commented
I tested the python api command oms.exportSSVTemplate("model", "template.ssv") with the latest nightly windows minGW build. However, I get the following error: 'OMSimulator' object has no attribute 'exportSSVTemplate'.
Did I missunderstand you @arun3688, is the python api for this ticket not yet inplemented?

2020-11-19 13:42 UTC, arun3688 commented
@robha67 It is implemented, but the submodule is not merged with OpenModelica master i guess, So it is not available with the nightly builds

2020-11-19 14:16 UTC, robha67 commented
I am not using the OpenModelica Nightly build. I tried with the MinGW 64bit OMSimulator build (OMSimulator-mingw64-v2.0.0.post258-g3135d7a.zip).

2020-11-19 15:12 UTC, arun3688 commented
@robha67 I think you are using `mingw binaries` and trying to execute in `windows` i guess,  Please download the windows binaries
https://build.openmodelica.org/omsimulator/win-msvc64/OMSimulator-win64-v2.0.0.post258-g3135d7a.zip and test it , I tested myself and it works.